### ISSUE TITLE
no start error

### ISSUE THREAD

**Issue by lan7ium** [jarulsamy/Plex-Bot#15]
Impossible to launch the container 
several errors occur when I run the docker yet I follow the instructions to the letter:

Sorry I'm french !

Creating network "plexbot_default" with the default driver
Creating PlexBot ...
Creating PlexBot ... done
Attaching to PlexBot
PlexBot     | 2021-01-19 05:17:34,716 WARNING: [bot.py:177 -             __init__() ] No lyrics token specified, lyrics disabled
PlexBot     | Traceback (most recent call last):
PlexBot     |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
PlexBot     |     "__main__", mod_spec)
PlexBot     |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
PlexBot     |     exec(code, run_globals)
PlexBot     |   File "/src/PlexBot/__main__.py", line 44, in <module>
PlexBot     |     bot.add_cog(Plex(bot, **plex_args))
PlexBot     |   File "/src/PlexBot/bot.py", line 182, in __init__
PlexBot     |     self.pms = PlexServer(self.base_url, self.plex_token)
PlexBot     |   File "/usr/local/lib/python3.7/site-packages/plexapi/server.py", line 110, in __init__
PlexBot     |     data = self.query(self.key, timeout=timeout)
PlexBot     |   File "/usr/local/lib/python3.7/site-packages/plexapi/server.py", line 444, in query
PlexBot     |     return ElementTree.fromstring(data) if data.strip() else None
PlexBot     |   File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
PlexBot     |     parser.feed(text)
PlexBot     | xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 24, column 45
PlexBot exited with code {u'StatusCode': 1, u'Error': None}

**Comment by jarulsamy** [comment]
Hi thanks for the issue report. Sorry for the troubles.

Could you post your `config.yaml`? You can omit the tokens. 

I am unable to reproduce this issue on my local machines.
