### ISSUE TITLE
Bot can't connect to Plex

### ISSUE THREAD

**Issue by Raventhicc** [jarulsamy/Plex-Bot#24]
```
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/src/PlexBot/__main__.py", line 44, in <module>

    bot.add_cog(Plex(bot, **plex_args))

  File "/src/PlexBot/bot.py", line 192, in __init__

    self.pms = PlexServer(self.base_url, self.plex_token)

  File "/usr/local/lib/python3.7/site-packages/plexapi/server.py", line 110, in __init__

    data = self.query(self.key, timeout=timeout)

  File "/usr/local/lib/python3.7/site-packages/plexapi/server.py", line 432, in query

    response = method(url, headers=headers, timeout=timeout, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 555, in get

    return self.request('GET', url, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85981abcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by Raventhicc** [comment]
using localhost IP instead of 127.0.0.1 fixed said issue
